name: ElytraSpeed
main: ru.ddiimmoonn.elytraspeed.ElytraSpeedPlugin
version: 1.0
api-version: 1.20
commands:
  gelytra:
    description: Give a custom elytra (level 1) to yourself or player.
    usage: /gelytra [player]
    permission: elytraspeed.give
permissions:
  elytraspeed.give:
    default: op
